### PR TITLE
bumping to v5.0.0 (elm 0.19 compatible)

### PR DESCRIPTION
**Pull request by Bastes**

### CODE REVIEW

**Comment by Bastes** [comment]
And here's the PR :) (provided it doesn't disappears into github limbo again ^^°).

**Comment by svoynow** [comment]
cool. I'll publish it to elm packages once I refresh my memory about how to do that ;)

**Comment by Bastes** [comment]
Thanks :)

Memory serves it's: `elm publish`

**Comment by svoynow** [comment]
published: https://package.elm-lang.org/packages/labzero/elm-google-geocoding/5.0.0/

**Comment by Bastes** [comment]
Yay :) 👍 Thanks a bunch.

**Pull request merged**
