### PR TITLE
Update to Elm 0.19.

### PR DESCRIPTION
**Pull request by 4onen**
Updated to Elm 0.19 because a package relying on this has examples that want this package. Not 100% sure this module is completely working on Elm 0.19, but all the tests pass without any changes beyond converting them to the new elm-explorations/elm-test version. There's some areas where Elm 0.19 could help this module, too: maybe using elm/url to build the URLs rather than relying on its percentEncode method to replace Http.encodeURI?

Let me know what you think!

### CODE REVIEW

**Comment by Bastes** [comment]
This looks legit :) how about merging it?

**Review by svoynow — APPROVED** [review]
Thanks for doing this!

**Comment by Bastes** [comment]
Yay :) thanks all 👍

**Comment by Bastes** [comment]
Problem with the PR: there is no version bump. I've cloned the repo and would like to prepare PR (already committed it) but...

...github's bugging and I can't PR nor see my repo :/

So here's a patch:
```diff
diff --git a/elm.json b/elm.json
index 11a136b..078b457 100644
--- a/elm.json
+++ b/elm.json
@@ -3,13 +3,14 @@
     "name": "labzero/elm-google-geocoding",
     "summary": "Elm interface to the Google Geocoding API",
     "license": "BSD-3-Clause",
-    "version": "4.0.1",
+    "version": "5.0.0",
     "exposed-modules": [
         "Geocoding"
     ],
     "elm-version": "0.19.0 <= v < 0.20.0",
     "dependencies": {
         "NoRedInk/elm-json-decode-pipeline": "1.0.0 <= v < 2.0.0",
+        "elm/core": "1.0.0 <= v < 2.0.0",
         "elm/http": "1.0.0 <= v < 2.0.0",
         "elm/json": "1.0.0 <= v < 2.0.0",
         "elm/url": "1.0.0 <= v < 2.0.0"
```

If anybody reads this before I've made my PR and can apply the patch and upgrade the library, I'd be immensely grateful for the upgrade (currently I'm stuck halfway through my migration because of this ^^°).

If not, there will be a PR as soon as github's done acting up.

**Pull request merged**
